#include "web.h"

#include <Arduino.h>
#include <WiFi.h>
#include <esp_http_server.h>

#include <cstdio>
#include <cstdlib>
#include <cstring>

#include "../assets/index.html.h"  // embedded web UI (generated by `mise run hexdump`)
#include "config.h"

namespace {

// httpd handlers run in their own task, so the control loop (loop()) and the web
// server are two execution contexts. This mux guards the small shared state
// below; critical sections only copy a few scalars, so they never stall control.
portMUX_TYPE mux = portMUX_INITIALIZER_UNLOCKED;

struct Shared {
  // Pending command (web -> control loop). Consumed and cleared by poll() / pollArm().
  Pid::Gains cmd_gains{config::kKp, config::kKi, config::kKd};
  float cmd_setpoint = config::kSetpointDeg;
  bool cmd_pending = false;
  int cmd_enable = -1;  // arm/disarm request: 1 arm, 0 disarm, -1 none

  // Latest telemetry (control loop -> web), for the /telemetry endpoint.
  float angle = 0.0f;
  bool enabled = false;
  bool tripped = false;
  bool bench = false;  // a serial bench/calibration command is driving the motors directly
  Pid::Gains gains{config::kKp, config::kKi, config::kKd};
  float setpoint = config::kSetpointDeg;
};
Shared g;

httpd_handle_t server = nullptr;

constexpr float clampf(float v, float lo, float hi) { return v < lo ? lo : (v > hi ? hi : v); }

// Serves the single-page UI (telemetry line, ARM/DISARM buttons, setpoint + PID sliders) from
// assets/index.html, embedded as a PROGMEM byte array. ARM toggles the software master-enable
// (the control loop); the ESC supply is gated by a separate hardware switch. Sent with an
// explicit length since the array is not NUL-terminated.
esp_err_t indexHandler(httpd_req_t* req) {
  httpd_resp_set_type(req, "text/html");
  return httpd_resp_send(req, reinterpret_cast<const char*>(index_html), index_html_len);
}

esp_err_t telemetryHandler(httpd_req_t* req) {
  taskENTER_CRITICAL(&mux);
  const Shared s = g;
  taskEXIT_CRITICAL(&mux);

  char buf[256];
  const int n = snprintf(buf, sizeof(buf),
                         "{\"angle\":%.2f,\"enabled\":%s,\"tripped\":%s,\"bench\":%s,"
                         "\"kp\":%.5f,\"ki\":%.5f,\"kd\":%.5f,\"sp\":%.2f}",
                         s.angle, s.enabled ? "true" : "false", s.tripped ? "true" : "false",
                         s.bench ? "true" : "false", s.gains.kp, s.gains.ki, s.gains.kd, s.setpoint);
  // snprintf returns the length it *would* have written; guard against passing a
  // truncated/oversized length to httpd_resp_send (which would over-read buf).
  if (n < 0 || n >= static_cast<int>(sizeof(buf))) {
    httpd_resp_send_500(req);
    return ESP_FAIL;
  }
  httpd_resp_set_type(req, "application/json");
  return httpd_resp_send(req, buf, n);
}

// GET /set?kp=..&ki=..&kd=..&sp=..&en=0|1  — any subset. Stages gains/setpoint and/or an
// arm/disarm request for the control loop to apply on its next step. en=1 arms, en=0 disarms;
// the control loop owns `enabled` (and boots disarmed). Parsing stays outside the lock —
// string/float parsing must not run with interrupts disabled on the WiFi core.
esp_err_t setHandler(httpd_req_t* req) {
  char query[128];
  if (httpd_req_get_url_query_str(req, query, sizeof(query)) == ESP_OK) {
    char v[32];  // reused; each lookup rewrites it before atof/atoi.
    const bool has_kp = httpd_query_key_value(query, "kp", v, sizeof(v)) == ESP_OK;
    const float kp = has_kp ? atof(v) : 0.0f;
    const bool has_ki = httpd_query_key_value(query, "ki", v, sizeof(v)) == ESP_OK;
    const float ki = has_ki ? atof(v) : 0.0f;
    const bool has_kd = httpd_query_key_value(query, "kd", v, sizeof(v)) == ESP_OK;
    const float kd = has_kd ? atof(v) : 0.0f;
    const bool has_sp = httpd_query_key_value(query, "sp", v, sizeof(v)) == ESP_OK;
    const float sp = has_sp ? atof(v) : 0.0f;
    const bool has_en = httpd_query_key_value(query, "en", v, sizeof(v)) == ESP_OK;
    const int en = has_en ? (atoi(v) ? 1 : 0) : -1;

    taskENTER_CRITICAL(&mux);
    if (has_kp) g.cmd_gains.kp = kp;
    if (has_ki) g.cmd_gains.ki = ki;
    if (has_kd) g.cmd_gains.kd = kd;
    if (has_sp) g.cmd_setpoint = sp;
    if (has_kp || has_ki || has_kd || has_sp) g.cmd_pending = true;
    if (has_en) g.cmd_enable = en;
    taskEXIT_CRITICAL(&mux);
  }
  return httpd_resp_sendstr(req, "ok");
}

// AP association diagnostics, at info level (LIBRA_LOG_LEVEL >= 3) so a connect attempt
// is visible in normal use. A STACONNECTED with no matching STADISCONNECTED means the
// client is on; a STADISCONNECTED reason code tells us why a join dropped.
void onWifiEvent(WiFiEvent_t event, WiFiEventInfo_t info) {
  if (event == ARDUINO_EVENT_WIFI_AP_STACONNECTED) {
    const uint8_t* m = info.wifi_ap_staconnected.mac;
    log_i("AP client joined %02x:%02x:%02x:%02x:%02x:%02x (aid=%d)", m[0], m[1], m[2], m[3], m[4], m[5],
          info.wifi_ap_staconnected.aid);
  } else if (event == ARDUINO_EVENT_WIFI_AP_STADISCONNECTED) {
    const auto& d = info.wifi_ap_stadisconnected;
    log_i("AP client left %02x:%02x:%02x:%02x:%02x:%02x (aid=%d)", d.mac[0], d.mac[1], d.mac[2], d.mac[3], d.mac[4],
          d.mac[5], d.aid);
  }
}

void registerUri(const char* path, esp_err_t (*handler)(httpd_req_t*)) {
  httpd_uri_t uri = {};
  uri.uri = path;
  uri.method = HTTP_GET;
  uri.handler = handler;
  httpd_register_uri_handler(server, &uri);
}

}  // namespace

namespace web {

bool begin() {
  WiFi.onEvent(onWifiEvent);  // log AP client join/leave (+ disconnect reason)
  WiFi.mode(WIFI_AP);
  // The UI can arm/disarm (the software master-enable; boots disarmed), so on an OPEN AP
  // any client could arm — set a WPA2 password (LIBRA_AP_PASS, >= 8 chars) when props are
  // on or others are in range. Empty = open (default); a shorter non-empty value is
  // rejected here and we fall back to an open AP.
  const bool secured = strlen(config::kApPass) >= 8;
  if (strlen(config::kApPass) > 0 && !secured) {
    log_w("LIBRA_AP_PASS too short (< 8 chars) — starting an OPEN AP instead");
  }
  const bool ok = secured ? WiFi.softAP(config::kApSsid, config::kApPass) : WiFi.softAP(config::kApSsid);
  if (!ok) {
    log_e("WiFi SoftAP failed");
    return false;
  }
  // Defensive: disable STA modem power-save. A no-op in pure AP mode (the AP keeps its
  // receiver on regardless), but correct if a STA mode is ever added.
  WiFi.setSleep(false);

  httpd_config_t cfg = HTTPD_DEFAULT_CONFIG();
  cfg.server_port = 80;
  // Pin httpd to core 0 — the PRO core that runs the WiFi/lwIP stack on the dual-core
  // WROOM, and the only core on the single-core C3. Keeps it off the control task,
  // which is pinned to the APP core (1) on the WROOM. Correct on both archs.
  cfg.core_id = 0;
  cfg.lru_purge_enable = true;
  if (httpd_start(&server, &cfg) != ESP_OK) {
    log_e("HTTP server failed to start");
    return false;
  }
  registerUri("/", indexHandler);
  registerUri("/telemetry", telemetryHandler);
  registerUri("/set", setHandler);

  log_i("web UI on %s AP '%s' -> http://%s/", secured ? "WPA2" : "open", config::kApSsid,
        WiFi.softAPIP().toString().c_str());
  return true;
}

void publish(float angle, bool enabled, bool tripped, bool bench, const Pid::Gains& gains, float setpoint) {
  taskENTER_CRITICAL(&mux);
  g.angle = angle;
  g.enabled = enabled;
  g.tripped = tripped;
  g.bench = bench;
  g.gains = gains;
  g.setpoint = setpoint;
  taskEXIT_CRITICAL(&mux);
}

bool poll(Pid::Gains& gains, float& setpoint) {
  taskENTER_CRITICAL(&mux);
  const bool pending = g.cmd_pending;
  Pid::Gains cmd_gains = g.cmd_gains;
  float cmd_setpoint = g.cmd_setpoint;
  g.cmd_pending = false;
  taskEXIT_CRITICAL(&mux);

  if (!pending) return false;
  gains = cmd_gains;
  // Never let a remote client target a tilt past the failsafe.
  setpoint = clampf(cmd_setpoint, -config::kTiltLimitDeg, config::kTiltLimitDeg);
  return true;
}

int pollArm() {
  taskENTER_CRITICAL(&mux);
  const int req = g.cmd_enable;
  g.cmd_enable = -1;
  taskEXIT_CRITICAL(&mux);
  return req;
}

}  // namespace web
