#include "web.h"

#include <Arduino.h>  // defines PROGMEM, used by the generated index.html.h
#include <esp_camera.h>
#include <esp_http_server.h>

#include <cstdio>
#include <cstdlib>
#include <cstring>

#include "control_state.h"
#include "index.html.h"  // PROGMEM: index_html[], index_html_len (generated by `mise run hexdump`)

namespace {

httpd_handle_t control_server = nullptr;
httpd_handle_t stream_server = nullptr;

constexpr char kStreamContentType[] = "multipart/x-mixed-replace;boundary=frame";
constexpr char kStreamBoundary[] = "\r\n--frame\r\n";
constexpr char kStreamPartFmt[] = "Content-Type: image/jpeg\r\nContent-Length: %u\r\n\r\n";

esp_err_t indexHandler(httpd_req_t* req) {
  httpd_resp_set_type(req, "text/html");
  return httpd_resp_send(req, reinterpret_cast<const char*>(index_html), index_html_len);
}

esp_err_t telemetryHandler(httpd_req_t* req) {
  const Telemetry t = state::telemetry();
  const Commands c = state::commands();
  char buf[320];
  const int n = snprintf(buf, sizeof(buf),
                         "{\"angle\":%.2f,\"out\":%.3f,\"m1\":%.2f,\"m2\":%.2f,"
                         "\"enabled\":%s,\"tripped\":%s,"
                         "\"kp\":%.5f,\"ki\":%.5f,\"kd\":%.5f,\"sp\":%.2f}",
                         t.angle, t.output, t.m1, t.m2, t.enabled ? "true" : "false", t.tripped ? "true" : "false",
                         c.gains.kp, c.gains.ki, c.gains.kd, c.setpoint);
  // snprintf returns the length it *would* have written; guard against passing a
  // truncated/oversized length to httpd_resp_send (which would over-read buf).
  if (n < 0 || n >= static_cast<int>(sizeof(buf))) {
    httpd_resp_send_500(req);
    return ESP_FAIL;
  }
  httpd_resp_set_type(req, "application/json");
  return httpd_resp_send(req, buf, n);
}

// GET /set?kp=..&ki=..&kd=..&sp=..&enabled=0|1  — any subset of params.
esp_err_t setHandler(httpd_req_t* req) {
  char query[160];
  if (httpd_req_get_url_query_str(req, query, sizeof(query)) == ESP_OK) {
    char v[32];
    if (httpd_query_key_value(query, "kp", v, sizeof(v)) == ESP_OK) state::setKp(atof(v));
    if (httpd_query_key_value(query, "ki", v, sizeof(v)) == ESP_OK) state::setKi(atof(v));
    if (httpd_query_key_value(query, "kd", v, sizeof(v)) == ESP_OK) state::setKd(atof(v));
    if (httpd_query_key_value(query, "sp", v, sizeof(v)) == ESP_OK) state::setSetpoint(atof(v));
    if (httpd_query_key_value(query, "enabled", v, sizeof(v)) == ESP_OK) state::setEnabled(v[0] == '1' || v[0] == 't');
  }
  return httpd_resp_sendstr(req, "ok");
}

esp_err_t streamHandler(httpd_req_t* req) {
  esp_err_t res = httpd_resp_set_type(req, kStreamContentType);
  if (res != ESP_OK) return res;
  httpd_resp_set_hdr(req, "X-Framerate", "30");

  while (true) {
    camera_fb_t* fb = esp_camera_fb_get();
    if (!fb) {
      res = ESP_FAIL;
      break;
    }
    char part[64];
    const size_t part_len = snprintf(part, sizeof(part), kStreamPartFmt, fb->len);

    res = httpd_resp_send_chunk(req, kStreamBoundary, strlen(kStreamBoundary));
    if (res == ESP_OK) res = httpd_resp_send_chunk(req, part, part_len);
    if (res == ESP_OK) res = httpd_resp_send_chunk(req, reinterpret_cast<const char*>(fb->buf), fb->len);

    esp_camera_fb_return(fb);
    if (res != ESP_OK) break;  // client disconnected
  }
  return res;
}

void registerUri(httpd_handle_t server, const char* path, esp_err_t (*handler)(httpd_req_t*)) {
  httpd_uri_t uri = {};
  uri.uri = path;
  uri.method = HTTP_GET;
  uri.handler = handler;
  httpd_register_uri_handler(server, &uri);
}

}  // namespace

bool webStart() {
  httpd_config_t cfg = HTTPD_DEFAULT_CONFIG();
  cfg.server_port = 80;
  cfg.ctrl_port = 32768;
  cfg.core_id = 0;
  cfg.lru_purge_enable = true;
  if (httpd_start(&control_server, &cfg) != ESP_OK) return false;
  registerUri(control_server, "/", indexHandler);
  registerUri(control_server, "/telemetry", telemetryHandler);
  registerUri(control_server, "/set", setHandler);

  httpd_config_t scfg = HTTPD_DEFAULT_CONFIG();
  scfg.server_port = 81;
  scfg.ctrl_port = 32769;
  scfg.core_id = 0;
  scfg.lru_purge_enable = true;
  if (httpd_start(&stream_server, &scfg) != ESP_OK) return false;
  registerUri(stream_server, "/stream", streamHandler);

  return true;
}
